name: CI

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/btj/ocaml-gtk-build-env:main
      options: --user root
      
    steps:
    - uses: actions/checkout@v3
    - name: Build ocaml-gtk
      run: |
        chmod ugo+w .
        eval `sudo -u opam opam env`
        PREFIX=/usr/lib/x86_64-linux-gnu dune build
