name: CI

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install required Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libgtk-4-dev gobject-introspection gir1.2-glib-2.0 gir1.2-gtk-4.0 bubblewrap
    - name: Install OPAM
      run: |
        echo '' | bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
        opam init
        opam install dune dune-configurator
    - name: Build ocaml-gtk
      run: dune build
      env:
        PREFIX: /usr/lib/x86_64-linux-gnu
