name: CI

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-22.04
    container: ocaml/opam:ubuntu-22.04-ocaml-4.14

    steps:
    - uses: actions/checkout@v3
    - name: Install required Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libgtk-4-dev gobject-introspection gir1.2-glib-2.0 gir1.2-gtk-4.0 bubblewrap
    - name: Install Dune
      run: opam install -y dune dune-configurator
    - name: Build ocaml-gtk
      run: |
        eval `opam env`
        dune build
      env:
        PREFIX: /usr/lib/x86_64-linux-gnu
